package enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum ClientsAppsPwa {
    S2BV52("s2b"),
    S2BV53("s2b"),
    PODOROGNIK("podorognik"),
    CAPITALSKILLS("capitalskills"),
    GILIS("gilis"),
    KANKADZESCHOOL("kankadzeschool"),
    MYELISACLUB("myelisaclub"),
    DELAYT("delayt"),
    GUSIGROUP("gusigroup"),
    MYSTERIOHOTEL("mysteriohotel"),
    LEOLECLER("leolecler"),
    ZUB33("33zub"),
    GDERAKI("gderaki"),
    PIVNOJDVORIK("pivnojdvorik"),
    TABASKOFRIENDS("tabaskofriends"),
    IZBA("izba"),
    MPRSHOP("mprshop"),
    MAYAKOVSKIHOTEL("mayakovskihotel"),
    MYASNOYBARON("myasnoybaron"),
    FRIENDSCLUB("friendsclub"),
    CHB_ADMIN("chb_admin"),
    AVTOMIR("avtomir"),
    INJIR("injir"),
    PARSPB("parspb"),
    KIMCHI("kimchi"),
    EXPRESSBUKET24("expressbuket24"),
    JETSONNEW("jetsonnew"),
    VOSHODVAPESHOP("voshodvapeshop"),
    RIVERSIDE("riverside"),
    GMB("gmb"),
    TARELKA("tarelka"),
    TOYSWAGON("toyswagon"),
    YARUMEN("yarumen"),
    COFFEEMAKE("coffeemake"),
    UMIKITCHEN("umikitchen"),
    MONACOCLINIC("monacoclinic"),
    ELECTRABIKE("electrabike"),
    NARUTORAMEN("narutoramen"),
    PERMGAZGARANT("permgazgarant"),
    FRANZ("franz"),
    VSEHOROSHO("vsehorosho"),
    PLATAN("platan"),
    SANTEHCITY("santehcity"),
    EXPERT3D("3dexpert"),
    SBBURGERS("sbburgers"),
    YABLOKI("yabloki"),
    BIGSHOP("bigshop"),
    CRYSTALHOUSE("crystalhouse"),
    KOSOUHOFF29("kosouhoff29"),
    LEDESSERT("ledessert"),
    CHOCOLANTINI("chocolantini"),
    VSHOP("vshop"),
    DAYNAVA("daynava"),
    NELLAFORESTA("nellaforesta"),
    TIMEBIZ("timebiz"),
    SWEETV("sweetv"),
    HMELSOLOD("hmelsolod"),
    ANTU("antu"),
    COFFEANA("coffeana"),
    DIETICA("dietica"),
    TSARSKAYA_OHOTA("tsarskaya_ohota"),
    RIVERMC("rivermc"),
    CHILLISBAR("chillisbar"),
    VELSKIY("velskiy"),
    KEYCOFFEE("keycoffee"),
    TMSHE("tmshe"),
    PIVOPEI("pivopei"),
    GOODTASTEFAMILY("goodtastefamily"),
    RUDENTA("rudenta"),
    WINECANDANCE("winecandance\n");

    @Getter
    public final String nameClient;
}
